/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class timestop_ru_Main */

#ifndef _Included_timestop_ru_Main
#define _Included_timestop_ru_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     timestop_ru_Main
 * Method:    get
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_timestop_ru_Main_get
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
